name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        go-version: ["1.18", "1.19"]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Go dependencies
        run: go mod download
        env:
          GOPROXY: "https://proxy.golang.org"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
